export const categories = [
  { value: "English Vocabulary", label: "English Vocabulary" },
  { value: "Grammar", label: "Grammar" },
  { value: "Reading", label: "Reading" },
  { value: "Idioms and Expressions", label: "Idioms and Expressions" },
  { value: "Translation", label: "Translation" },
  { value: "Japanese", label: "Japanese" },
  { value: "Spanish", label: "Spanish" },
  { value: "French", label: "French" },
  { value: "German", label: "German" },
  { value: "Chinese", label: "Chinese" },
  { value: "Korean", label: "Korean" },
  { value: "General Knowledge", label: "General Knowledge" },
  { value: "Math", label: "Math" },
  { value: "Science", label: "Science" },
  { value: "History", label: "History" },
  { value: "Geography", label: "Geography" },
  { value: "Literature", label: "Literature" },
  { value: "Movies", label: "Movies" },
  { value: "Music", label: "Music" },
  { value: "Sports", label: "Sports" },
  { value: "Art", label: "Art" },
  { value: "Pop Culture", label: "Pop Culture" },
  { value: "Technology", label: "Technology" },
  { value: "Food and Drink", label: "Food and Drink" },
  { value: "Travel", label: "Travel" },
  { value: "Business", label: "Business" },
];
