import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/layouts/Header";
import { Toaster } from "@/components/ui/toaster";
import LoginHeader from "../components/layouts/LoginHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <LoginHeader />
    {children}
    <Toaster />
    </>
  );
}
