import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import SideBar from "../components/layouts/SideBar";
import Footer from "../components/layouts/Footer";
import QuizHeader from "../components/layouts/QuizHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <QuizHeader />
      <div className="mt-[74px] flex flex-col min-h-screen">
        <div className="lg:grid lg:grid-cols-[250px_1fr] flex-1">
          <div className="hidden lg:block lg:h-full  lg:border-r">
            <div className="lg:mx-auto lg:max-w-[173px]">
              <SideBar />
            </div>
          </div>
          <div className="lg:col-span-1">
            {children}
            <Toaster />
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
