import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import SideBar from "../components/layouts/SideBar";
import Footer from "../components/layouts/Footer";
import QuizHeader from "../components/layouts/QuizHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <QuizHeader />
      <div className="mt-[74px] flex flex-col overflow-none" style={{ minHeight: 'calc(100vh - 148px)' }}>
          {children}
          <Toaster />
      </div>
    </>
  );
}
